import {
  Users,
  BookOpen,
  GraduationCap,
  Award,
  Microscope,
  TrendingUp,
  Building2,
  Trophy,
  Home,
  Heart,
  AlertCircle,
  Calendar,
  CheckCircle,
  Download,
  Eye,
  Target,
  Compass,
  Lightbulb,
  Globe,
  ChevronRight,
  ChevronLeft,
  Mail,
  Phone,
  ExternalLink,
  Clock,
  Library,
  Database,
  Shield,
  Scale,
  Search,
  ListFilter,
  FileText,
  type LucideIcon,
} from "lucide-react";

/**
 * String-keyed registry mapping JSON `icon` fields to lucide components.
 * JSON content can't hold component references, so section data stores
 * a key from this map and the component resolves it at render time.
 */
export const iconMap = {
  users: Users,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  award: Award,
  microscope: Microscope,
  "trending-up": TrendingUp,
  building: Building2,
  trophy: Trophy,
  home: Home,
  heart: Heart,
  "alert-circle": AlertCircle,
  calendar: Calendar,
  "check-circle": CheckCircle,
  download: Download,
  eye: Eye,
  target: Target,
  compass: Compass,
  lightbulb: Lightbulb,
  globe: Globe,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  mail: Mail,
  phone: Phone,
  "external-link": ExternalLink,
  clock: Clock,
  library: Library,
  database: Database,
  shield: Shield,
  scale: Scale,
  search: Search,
  "list-filter": ListFilter,
  "file-text": FileText,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
